# For more information do to https://github.com/kontent-ai/kontent-ai.github.io/blob/main/docs/articles/JavaScript-Node.js-GitHub-Actions-Guidelines.md

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: latest
    - run: npm ci
    - run: npm run build
    - name: Deploy 🚀
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: "build"
